//@ts-nocheck
  // DO NOT MODIFY THIS FILE. This file is automatically generated by Tina
  export function gql(strings: TemplateStringsArray, ...args: string[]): string {
    let str = ''
    strings.forEach((string, i) => {
      str += string + (args[i] || '')
    })
    return str
  }
  export type Maybe<T> = T | null;
export type InputMaybe<T> = Maybe<T>;
export type Exact<T extends { [key: string]: unknown }> = { [K in keyof T]: T[K] };
export type MakeOptional<T, K extends keyof T> = Omit<T, K> & { [SubKey in K]?: Maybe<T[SubKey]> };
export type MakeMaybe<T, K extends keyof T> = Omit<T, K> & { [SubKey in K]: Maybe<T[SubKey]> };
export type MakeEmpty<T extends { [key: string]: unknown }, K extends keyof T> = { [_ in K]?: never };
export type Incremental<T> = T | { [P in keyof T]?: P extends ' $fragmentName' | '__typename' ? T[P] : never };
/** All built-in and custom scalars, mapped to their actual values */
export type Scalars = {
  ID: { input: string; output: string; }
  String: { input: string; output: string; }
  Boolean: { input: boolean; output: boolean; }
  Int: { input: number; output: number; }
  Float: { input: number; output: number; }
  /** References another document, used as a foreign key */
  Reference: { input: any; output: any; }
  JSON: { input: any; output: any; }
};

export type SystemInfo = {
  __typename?: 'SystemInfo';
  filename: Scalars['String']['output'];
  title?: Maybe<Scalars['String']['output']>;
  basename: Scalars['String']['output'];
  hasReferences?: Maybe<Scalars['Boolean']['output']>;
  breadcrumbs: Array<Scalars['String']['output']>;
  path: Scalars['String']['output'];
  relativePath: Scalars['String']['output'];
  extension: Scalars['String']['output'];
  template: Scalars['String']['output'];
  collection: Collection;
};


export type SystemInfoBreadcrumbsArgs = {
  excludeExtension?: InputMaybe<Scalars['Boolean']['input']>;
};

export type Folder = {
  __typename?: 'Folder';
  name: Scalars['String']['output'];
  path: Scalars['String']['output'];
};

export type PageInfo = {
  __typename?: 'PageInfo';
  hasPreviousPage: Scalars['Boolean']['output'];
  hasNextPage: Scalars['Boolean']['output'];
  startCursor: Scalars['String']['output'];
  endCursor: Scalars['String']['output'];
};

export type Node = {
  id: Scalars['ID']['output'];
};

export type Document = {
  id: Scalars['ID']['output'];
  _sys?: Maybe<SystemInfo>;
  _values: Scalars['JSON']['output'];
};

/** A relay-compliant pagination connection */
export type Connection = {
  totalCount: Scalars['Float']['output'];
  pageInfo: PageInfo;
};

export type Query = {
  __typename?: 'Query';
  getOptimizedQuery?: Maybe<Scalars['String']['output']>;
  collection: Collection;
  collections: Array<Collection>;
  node: Node;
  document: DocumentNode;
  global: Global;
  globalConnection: GlobalConnection;
  home: Home;
  homeConnection: HomeConnection;
  batteries: Batteries;
  batteriesConnection: BatteriesConnection;
  service: Service;
  serviceConnection: ServiceConnection;
  equipment: Equipment;
  equipmentConnection: EquipmentConnection;
  racking: Racking;
  rackingConnection: RackingConnection;
  parts: Parts;
  partsConnection: PartsConnection;
};


export type QueryGetOptimizedQueryArgs = {
  queryString: Scalars['String']['input'];
};


export type QueryCollectionArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
};


export type QueryNodeArgs = {
  id?: InputMaybe<Scalars['String']['input']>;
};


export type QueryDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryGlobalArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryGlobalConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<GlobalFilter>;
};


export type QueryHomeArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryHomeConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<HomeFilter>;
};


export type QueryBatteriesArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryBatteriesConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<BatteriesFilter>;
};


export type QueryServiceArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryServiceConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<ServiceFilter>;
};


export type QueryEquipmentArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryEquipmentConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<EquipmentFilter>;
};


export type QueryRackingArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryRackingConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<RackingFilter>;
};


export type QueryPartsArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryPartsConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<PartsFilter>;
};

export type DocumentFilter = {
  global?: InputMaybe<GlobalFilter>;
  home?: InputMaybe<HomeFilter>;
  batteries?: InputMaybe<BatteriesFilter>;
  service?: InputMaybe<ServiceFilter>;
  equipment?: InputMaybe<EquipmentFilter>;
  racking?: InputMaybe<RackingFilter>;
  parts?: InputMaybe<PartsFilter>;
};

export type DocumentConnectionEdges = {
  __typename?: 'DocumentConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<DocumentNode>;
};

export type DocumentConnection = Connection & {
  __typename?: 'DocumentConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<DocumentConnectionEdges>>>;
};

export type Collection = {
  __typename?: 'Collection';
  name: Scalars['String']['output'];
  slug: Scalars['String']['output'];
  label?: Maybe<Scalars['String']['output']>;
  path: Scalars['String']['output'];
  format?: Maybe<Scalars['String']['output']>;
  matches?: Maybe<Scalars['String']['output']>;
  templates?: Maybe<Array<Maybe<Scalars['JSON']['output']>>>;
  fields?: Maybe<Array<Maybe<Scalars['JSON']['output']>>>;
  documents: DocumentConnection;
};


export type CollectionDocumentsArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<DocumentFilter>;
  folder?: InputMaybe<Scalars['String']['input']>;
};

export type DocumentNode = Global | Home | Batteries | Service | Equipment | Racking | Parts | Folder;

export type Global = Node & Document & {
  __typename?: 'Global';
  companyName: Scalars['String']['output'];
  phone: Scalars['String']['output'];
  email: Scalars['String']['output'];
  address?: Maybe<Scalars['String']['output']>;
  hours?: Maybe<Scalars['String']['output']>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type StringFilter = {
  startsWith?: InputMaybe<Scalars['String']['input']>;
  eq?: InputMaybe<Scalars['String']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
  in?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
};

export type GlobalFilter = {
  companyName?: InputMaybe<StringFilter>;
  phone?: InputMaybe<StringFilter>;
  email?: InputMaybe<StringFilter>;
  address?: InputMaybe<StringFilter>;
  hours?: InputMaybe<StringFilter>;
};

export type GlobalConnectionEdges = {
  __typename?: 'GlobalConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Global>;
};

export type GlobalConnection = Connection & {
  __typename?: 'GlobalConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<GlobalConnectionEdges>>>;
};

export type HomeHeroStats = {
  __typename?: 'HomeHeroStats';
  value?: Maybe<Scalars['String']['output']>;
  label?: Maybe<Scalars['String']['output']>;
};

export type HomeServices = {
  __typename?: 'HomeServices';
  badge?: Maybe<Scalars['String']['output']>;
  title: Scalars['String']['output'];
  description?: Maybe<Scalars['String']['output']>;
  link?: Maybe<Scalars['String']['output']>;
};

export type HomeWhyUs = {
  __typename?: 'HomeWhyUs';
  title: Scalars['String']['output'];
  description?: Maybe<Scalars['String']['output']>;
};

export type Home = Node & Document & {
  __typename?: 'Home';
  seoTitle: Scalars['String']['output'];
  seoDescription?: Maybe<Scalars['String']['output']>;
  heroBadge?: Maybe<Scalars['String']['output']>;
  heroTitle: Scalars['String']['output'];
  heroHighlight?: Maybe<Scalars['String']['output']>;
  heroDescription?: Maybe<Scalars['String']['output']>;
  heroCta1Text?: Maybe<Scalars['String']['output']>;
  heroCta1Link?: Maybe<Scalars['String']['output']>;
  heroCta2Text?: Maybe<Scalars['String']['output']>;
  heroCta2Link?: Maybe<Scalars['String']['output']>;
  heroStats?: Maybe<Array<Maybe<HomeHeroStats>>>;
  services?: Maybe<Array<Maybe<HomeServices>>>;
  batterySplitImage?: Maybe<Scalars['String']['output']>;
  batterySplitHeading?: Maybe<Scalars['String']['output']>;
  batterySplitText?: Maybe<Scalars['String']['output']>;
  batterySplitCtaText?: Maybe<Scalars['String']['output']>;
  batterySplitCtaLink?: Maybe<Scalars['String']['output']>;
  whyUs?: Maybe<Array<Maybe<HomeWhyUs>>>;
  equipmentSplitImage?: Maybe<Scalars['String']['output']>;
  equipmentSplitHeading?: Maybe<Scalars['String']['output']>;
  equipmentSplitText?: Maybe<Scalars['String']['output']>;
  equipmentSplitCtaText?: Maybe<Scalars['String']['output']>;
  equipmentSplitCtaLink?: Maybe<Scalars['String']['output']>;
  bannerImage?: Maybe<Scalars['String']['output']>;
  bannerHeading?: Maybe<Scalars['String']['output']>;
  bannerText?: Maybe<Scalars['String']['output']>;
  ctaHeading?: Maybe<Scalars['String']['output']>;
  ctaText?: Maybe<Scalars['String']['output']>;
  ctaCta1Text?: Maybe<Scalars['String']['output']>;
  ctaCta1Link?: Maybe<Scalars['String']['output']>;
  ctaCta2Text?: Maybe<Scalars['String']['output']>;
  ctaCta2Link?: Maybe<Scalars['String']['output']>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type HomeHeroStatsFilter = {
  value?: InputMaybe<StringFilter>;
  label?: InputMaybe<StringFilter>;
};

export type HomeServicesFilter = {
  badge?: InputMaybe<StringFilter>;
  title?: InputMaybe<StringFilter>;
  description?: InputMaybe<StringFilter>;
  link?: InputMaybe<StringFilter>;
};

export type ImageFilter = {
  startsWith?: InputMaybe<Scalars['String']['input']>;
  eq?: InputMaybe<Scalars['String']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
  in?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
};

export type HomeWhyUsFilter = {
  title?: InputMaybe<StringFilter>;
  description?: InputMaybe<StringFilter>;
};

export type HomeFilter = {
  seoTitle?: InputMaybe<StringFilter>;
  seoDescription?: InputMaybe<StringFilter>;
  heroBadge?: InputMaybe<StringFilter>;
  heroTitle?: InputMaybe<StringFilter>;
  heroHighlight?: InputMaybe<StringFilter>;
  heroDescription?: InputMaybe<StringFilter>;
  heroCta1Text?: InputMaybe<StringFilter>;
  heroCta1Link?: InputMaybe<StringFilter>;
  heroCta2Text?: InputMaybe<StringFilter>;
  heroCta2Link?: InputMaybe<StringFilter>;
  heroStats?: InputMaybe<HomeHeroStatsFilter>;
  services?: InputMaybe<HomeServicesFilter>;
  batterySplitImage?: InputMaybe<ImageFilter>;
  batterySplitHeading?: InputMaybe<StringFilter>;
  batterySplitText?: InputMaybe<StringFilter>;
  batterySplitCtaText?: InputMaybe<StringFilter>;
  batterySplitCtaLink?: InputMaybe<StringFilter>;
  whyUs?: InputMaybe<HomeWhyUsFilter>;
  equipmentSplitImage?: InputMaybe<ImageFilter>;
  equipmentSplitHeading?: InputMaybe<StringFilter>;
  equipmentSplitText?: InputMaybe<StringFilter>;
  equipmentSplitCtaText?: InputMaybe<StringFilter>;
  equipmentSplitCtaLink?: InputMaybe<StringFilter>;
  bannerImage?: InputMaybe<ImageFilter>;
  bannerHeading?: InputMaybe<StringFilter>;
  bannerText?: InputMaybe<StringFilter>;
  ctaHeading?: InputMaybe<StringFilter>;
  ctaText?: InputMaybe<StringFilter>;
  ctaCta1Text?: InputMaybe<StringFilter>;
  ctaCta1Link?: InputMaybe<StringFilter>;
  ctaCta2Text?: InputMaybe<StringFilter>;
  ctaCta2Link?: InputMaybe<StringFilter>;
};

export type HomeConnectionEdges = {
  __typename?: 'HomeConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Home>;
};

export type HomeConnection = Connection & {
  __typename?: 'HomeConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<HomeConnectionEdges>>>;
};

export type BatteriesLithiumCards = {
  __typename?: 'BatteriesLithiumCards';
  badge?: Maybe<Scalars['String']['output']>;
  title: Scalars['String']['output'];
  description?: Maybe<Scalars['String']['output']>;
};

export type BatteriesRejuvCards = {
  __typename?: 'BatteriesRejuvCards';
  title: Scalars['String']['output'];
  description?: Maybe<Scalars['String']['output']>;
};

export type BatteriesEquipCards = {
  __typename?: 'BatteriesEquipCards';
  title: Scalars['String']['output'];
  description?: Maybe<Scalars['String']['output']>;
};

export type Batteries = Node & Document & {
  __typename?: 'Batteries';
  seoTitle: Scalars['String']['output'];
  seoDescription?: Maybe<Scalars['String']['output']>;
  heroBadge?: Maybe<Scalars['String']['output']>;
  heroTitle?: Maybe<Scalars['String']['output']>;
  heroHighlight?: Maybe<Scalars['String']['output']>;
  heroDescription?: Maybe<Scalars['String']['output']>;
  heroCta1Text?: Maybe<Scalars['String']['output']>;
  heroCta1Link?: Maybe<Scalars['String']['output']>;
  heroCta2Text?: Maybe<Scalars['String']['output']>;
  heroCta2Link?: Maybe<Scalars['String']['output']>;
  lithiumHeading?: Maybe<Scalars['String']['output']>;
  lithiumSubtitle?: Maybe<Scalars['String']['output']>;
  lithiumCards?: Maybe<Array<Maybe<BatteriesLithiumCards>>>;
  splitImage?: Maybe<Scalars['String']['output']>;
  splitHeading?: Maybe<Scalars['String']['output']>;
  splitText?: Maybe<Scalars['String']['output']>;
  splitCtaText?: Maybe<Scalars['String']['output']>;
  splitCtaLink?: Maybe<Scalars['String']['output']>;
  rejuvHeading?: Maybe<Scalars['String']['output']>;
  rejuvSubtitle?: Maybe<Scalars['String']['output']>;
  rejuvCards?: Maybe<Array<Maybe<BatteriesRejuvCards>>>;
  rejuvCtaText?: Maybe<Scalars['String']['output']>;
  rejuvCtaLink?: Maybe<Scalars['String']['output']>;
  equipHeading?: Maybe<Scalars['String']['output']>;
  equipSubtitle?: Maybe<Scalars['String']['output']>;
  equipCards?: Maybe<Array<Maybe<BatteriesEquipCards>>>;
  ctaHeading?: Maybe<Scalars['String']['output']>;
  ctaText?: Maybe<Scalars['String']['output']>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type BatteriesLithiumCardsFilter = {
  badge?: InputMaybe<StringFilter>;
  title?: InputMaybe<StringFilter>;
  description?: InputMaybe<StringFilter>;
};

export type BatteriesRejuvCardsFilter = {
  title?: InputMaybe<StringFilter>;
  description?: InputMaybe<StringFilter>;
};

export type BatteriesEquipCardsFilter = {
  title?: InputMaybe<StringFilter>;
  description?: InputMaybe<StringFilter>;
};

export type BatteriesFilter = {
  seoTitle?: InputMaybe<StringFilter>;
  seoDescription?: InputMaybe<StringFilter>;
  heroBadge?: InputMaybe<StringFilter>;
  heroTitle?: InputMaybe<StringFilter>;
  heroHighlight?: InputMaybe<StringFilter>;
  heroDescription?: InputMaybe<StringFilter>;
  heroCta1Text?: InputMaybe<StringFilter>;
  heroCta1Link?: InputMaybe<StringFilter>;
  heroCta2Text?: InputMaybe<StringFilter>;
  heroCta2Link?: InputMaybe<StringFilter>;
  lithiumHeading?: InputMaybe<StringFilter>;
  lithiumSubtitle?: InputMaybe<StringFilter>;
  lithiumCards?: InputMaybe<BatteriesLithiumCardsFilter>;
  splitImage?: InputMaybe<ImageFilter>;
  splitHeading?: InputMaybe<StringFilter>;
  splitText?: InputMaybe<StringFilter>;
  splitCtaText?: InputMaybe<StringFilter>;
  splitCtaLink?: InputMaybe<StringFilter>;
  rejuvHeading?: InputMaybe<StringFilter>;
  rejuvSubtitle?: InputMaybe<StringFilter>;
  rejuvCards?: InputMaybe<BatteriesRejuvCardsFilter>;
  rejuvCtaText?: InputMaybe<StringFilter>;
  rejuvCtaLink?: InputMaybe<StringFilter>;
  equipHeading?: InputMaybe<StringFilter>;
  equipSubtitle?: InputMaybe<StringFilter>;
  equipCards?: InputMaybe<BatteriesEquipCardsFilter>;
  ctaHeading?: InputMaybe<StringFilter>;
  ctaText?: InputMaybe<StringFilter>;
};

export type BatteriesConnectionEdges = {
  __typename?: 'BatteriesConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Batteries>;
};

export type BatteriesConnection = Connection & {
  __typename?: 'BatteriesConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<BatteriesConnectionEdges>>>;
};

export type ServiceServiceCards = {
  __typename?: 'ServiceServiceCards';
  badge?: Maybe<Scalars['String']['output']>;
  title: Scalars['String']['output'];
  description?: Maybe<Scalars['String']['output']>;
};

export type ServiceEquipCards = {
  __typename?: 'ServiceEquipCards';
  title: Scalars['String']['output'];
  description?: Maybe<Scalars['String']['output']>;
};

export type Service = Node & Document & {
  __typename?: 'Service';
  seoTitle: Scalars['String']['output'];
  seoDescription?: Maybe<Scalars['String']['output']>;
  heroBadge?: Maybe<Scalars['String']['output']>;
  heroTitle?: Maybe<Scalars['String']['output']>;
  heroHighlight?: Maybe<Scalars['String']['output']>;
  heroDescription?: Maybe<Scalars['String']['output']>;
  heroCta1Text?: Maybe<Scalars['String']['output']>;
  heroCta1Link?: Maybe<Scalars['String']['output']>;
  heroCta2Text?: Maybe<Scalars['String']['output']>;
  heroCta2Link?: Maybe<Scalars['String']['output']>;
  serviceCards?: Maybe<Array<Maybe<ServiceServiceCards>>>;
  bannerImage?: Maybe<Scalars['String']['output']>;
  bannerHeading?: Maybe<Scalars['String']['output']>;
  bannerText?: Maybe<Scalars['String']['output']>;
  equipHeading?: Maybe<Scalars['String']['output']>;
  equipSubtitle?: Maybe<Scalars['String']['output']>;
  equipCards?: Maybe<Array<Maybe<ServiceEquipCards>>>;
  ctaHeading?: Maybe<Scalars['String']['output']>;
  ctaText?: Maybe<Scalars['String']['output']>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type ServiceServiceCardsFilter = {
  badge?: InputMaybe<StringFilter>;
  title?: InputMaybe<StringFilter>;
  description?: InputMaybe<StringFilter>;
};

export type ServiceEquipCardsFilter = {
  title?: InputMaybe<StringFilter>;
  description?: InputMaybe<StringFilter>;
};

export type ServiceFilter = {
  seoTitle?: InputMaybe<StringFilter>;
  seoDescription?: InputMaybe<StringFilter>;
  heroBadge?: InputMaybe<StringFilter>;
  heroTitle?: InputMaybe<StringFilter>;
  heroHighlight?: InputMaybe<StringFilter>;
  heroDescription?: InputMaybe<StringFilter>;
  heroCta1Text?: InputMaybe<StringFilter>;
  heroCta1Link?: InputMaybe<StringFilter>;
  heroCta2Text?: InputMaybe<StringFilter>;
  heroCta2Link?: InputMaybe<StringFilter>;
  serviceCards?: InputMaybe<ServiceServiceCardsFilter>;
  bannerImage?: InputMaybe<ImageFilter>;
  bannerHeading?: InputMaybe<StringFilter>;
  bannerText?: InputMaybe<StringFilter>;
  equipHeading?: InputMaybe<StringFilter>;
  equipSubtitle?: InputMaybe<StringFilter>;
  equipCards?: InputMaybe<ServiceEquipCardsFilter>;
  ctaHeading?: InputMaybe<StringFilter>;
  ctaText?: InputMaybe<StringFilter>;
};

export type ServiceConnectionEdges = {
  __typename?: 'ServiceConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Service>;
};

export type ServiceConnection = Connection & {
  __typename?: 'ServiceConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<ServiceConnectionEdges>>>;
};

export type EquipmentEquipCards = {
  __typename?: 'EquipmentEquipCards';
  badge?: Maybe<Scalars['String']['output']>;
  title: Scalars['String']['output'];
  description?: Maybe<Scalars['String']['output']>;
};

export type EquipmentWhyBuyCards = {
  __typename?: 'EquipmentWhyBuyCards';
  title: Scalars['String']['output'];
  description?: Maybe<Scalars['String']['output']>;
};

export type Equipment = Node & Document & {
  __typename?: 'Equipment';
  seoTitle: Scalars['String']['output'];
  seoDescription?: Maybe<Scalars['String']['output']>;
  heroBadge?: Maybe<Scalars['String']['output']>;
  heroTitle?: Maybe<Scalars['String']['output']>;
  heroHighlight?: Maybe<Scalars['String']['output']>;
  heroDescription?: Maybe<Scalars['String']['output']>;
  heroCta1Text?: Maybe<Scalars['String']['output']>;
  heroCta1Link?: Maybe<Scalars['String']['output']>;
  heroCta2Text?: Maybe<Scalars['String']['output']>;
  heroCta2Link?: Maybe<Scalars['String']['output']>;
  equipCards?: Maybe<Array<Maybe<EquipmentEquipCards>>>;
  bannerImage?: Maybe<Scalars['String']['output']>;
  bannerHeading?: Maybe<Scalars['String']['output']>;
  bannerText?: Maybe<Scalars['String']['output']>;
  inventoryHeading?: Maybe<Scalars['String']['output']>;
  inventorySubtitle?: Maybe<Scalars['String']['output']>;
  inventoryPlaceholder?: Maybe<Scalars['String']['output']>;
  whyBuyCards?: Maybe<Array<Maybe<EquipmentWhyBuyCards>>>;
  ctaHeading?: Maybe<Scalars['String']['output']>;
  ctaText?: Maybe<Scalars['String']['output']>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type EquipmentEquipCardsFilter = {
  badge?: InputMaybe<StringFilter>;
  title?: InputMaybe<StringFilter>;
  description?: InputMaybe<StringFilter>;
};

export type EquipmentWhyBuyCardsFilter = {
  title?: InputMaybe<StringFilter>;
  description?: InputMaybe<StringFilter>;
};

export type EquipmentFilter = {
  seoTitle?: InputMaybe<StringFilter>;
  seoDescription?: InputMaybe<StringFilter>;
  heroBadge?: InputMaybe<StringFilter>;
  heroTitle?: InputMaybe<StringFilter>;
  heroHighlight?: InputMaybe<StringFilter>;
  heroDescription?: InputMaybe<StringFilter>;
  heroCta1Text?: InputMaybe<StringFilter>;
  heroCta1Link?: InputMaybe<StringFilter>;
  heroCta2Text?: InputMaybe<StringFilter>;
  heroCta2Link?: InputMaybe<StringFilter>;
  equipCards?: InputMaybe<EquipmentEquipCardsFilter>;
  bannerImage?: InputMaybe<ImageFilter>;
  bannerHeading?: InputMaybe<StringFilter>;
  bannerText?: InputMaybe<StringFilter>;
  inventoryHeading?: InputMaybe<StringFilter>;
  inventorySubtitle?: InputMaybe<StringFilter>;
  inventoryPlaceholder?: InputMaybe<StringFilter>;
  whyBuyCards?: InputMaybe<EquipmentWhyBuyCardsFilter>;
  ctaHeading?: InputMaybe<StringFilter>;
  ctaText?: InputMaybe<StringFilter>;
};

export type EquipmentConnectionEdges = {
  __typename?: 'EquipmentConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Equipment>;
};

export type EquipmentConnection = Connection & {
  __typename?: 'EquipmentConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<EquipmentConnectionEdges>>>;
};

export type RackingRackingCards = {
  __typename?: 'RackingRackingCards';
  badge?: Maybe<Scalars['String']['output']>;
  title: Scalars['String']['output'];
  description?: Maybe<Scalars['String']['output']>;
};

export type RackingDockCards = {
  __typename?: 'RackingDockCards';
  title: Scalars['String']['output'];
  description?: Maybe<Scalars['String']['output']>;
};

export type Racking = Node & Document & {
  __typename?: 'Racking';
  seoTitle: Scalars['String']['output'];
  seoDescription?: Maybe<Scalars['String']['output']>;
  heroBadge?: Maybe<Scalars['String']['output']>;
  heroTitle?: Maybe<Scalars['String']['output']>;
  heroHighlight?: Maybe<Scalars['String']['output']>;
  heroDescription?: Maybe<Scalars['String']['output']>;
  heroCta1Text?: Maybe<Scalars['String']['output']>;
  heroCta1Link?: Maybe<Scalars['String']['output']>;
  rackingHeading?: Maybe<Scalars['String']['output']>;
  rackingSubtitle?: Maybe<Scalars['String']['output']>;
  rackingCards?: Maybe<Array<Maybe<RackingRackingCards>>>;
  bannerImage?: Maybe<Scalars['String']['output']>;
  bannerHeading?: Maybe<Scalars['String']['output']>;
  bannerText?: Maybe<Scalars['String']['output']>;
  dockHeading?: Maybe<Scalars['String']['output']>;
  dockSubtitle?: Maybe<Scalars['String']['output']>;
  dockCards?: Maybe<Array<Maybe<RackingDockCards>>>;
  ctaHeading?: Maybe<Scalars['String']['output']>;
  ctaText?: Maybe<Scalars['String']['output']>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type RackingRackingCardsFilter = {
  badge?: InputMaybe<StringFilter>;
  title?: InputMaybe<StringFilter>;
  description?: InputMaybe<StringFilter>;
};

export type RackingDockCardsFilter = {
  title?: InputMaybe<StringFilter>;
  description?: InputMaybe<StringFilter>;
};

export type RackingFilter = {
  seoTitle?: InputMaybe<StringFilter>;
  seoDescription?: InputMaybe<StringFilter>;
  heroBadge?: InputMaybe<StringFilter>;
  heroTitle?: InputMaybe<StringFilter>;
  heroHighlight?: InputMaybe<StringFilter>;
  heroDescription?: InputMaybe<StringFilter>;
  heroCta1Text?: InputMaybe<StringFilter>;
  heroCta1Link?: InputMaybe<StringFilter>;
  rackingHeading?: InputMaybe<StringFilter>;
  rackingSubtitle?: InputMaybe<StringFilter>;
  rackingCards?: InputMaybe<RackingRackingCardsFilter>;
  bannerImage?: InputMaybe<ImageFilter>;
  bannerHeading?: InputMaybe<StringFilter>;
  bannerText?: InputMaybe<StringFilter>;
  dockHeading?: InputMaybe<StringFilter>;
  dockSubtitle?: InputMaybe<StringFilter>;
  dockCards?: InputMaybe<RackingDockCardsFilter>;
  ctaHeading?: InputMaybe<StringFilter>;
  ctaText?: InputMaybe<StringFilter>;
};

export type RackingConnectionEdges = {
  __typename?: 'RackingConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Racking>;
};

export type RackingConnection = Connection & {
  __typename?: 'RackingConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<RackingConnectionEdges>>>;
};

export type PartsFeatureCards = {
  __typename?: 'PartsFeatureCards';
  badge?: Maybe<Scalars['String']['output']>;
  title: Scalars['String']['output'];
  description?: Maybe<Scalars['String']['output']>;
};

export type Parts = Node & Document & {
  __typename?: 'Parts';
  seoTitle: Scalars['String']['output'];
  seoDescription?: Maybe<Scalars['String']['output']>;
  heroBadge?: Maybe<Scalars['String']['output']>;
  heroTitle?: Maybe<Scalars['String']['output']>;
  heroHighlight?: Maybe<Scalars['String']['output']>;
  heroDescription?: Maybe<Scalars['String']['output']>;
  heroCta1Text?: Maybe<Scalars['String']['output']>;
  heroCta1Link?: Maybe<Scalars['String']['output']>;
  featureCards?: Maybe<Array<Maybe<PartsFeatureCards>>>;
  ctaHeading?: Maybe<Scalars['String']['output']>;
  ctaText?: Maybe<Scalars['String']['output']>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type PartsFeatureCardsFilter = {
  badge?: InputMaybe<StringFilter>;
  title?: InputMaybe<StringFilter>;
  description?: InputMaybe<StringFilter>;
};

export type PartsFilter = {
  seoTitle?: InputMaybe<StringFilter>;
  seoDescription?: InputMaybe<StringFilter>;
  heroBadge?: InputMaybe<StringFilter>;
  heroTitle?: InputMaybe<StringFilter>;
  heroHighlight?: InputMaybe<StringFilter>;
  heroDescription?: InputMaybe<StringFilter>;
  heroCta1Text?: InputMaybe<StringFilter>;
  heroCta1Link?: InputMaybe<StringFilter>;
  featureCards?: InputMaybe<PartsFeatureCardsFilter>;
  ctaHeading?: InputMaybe<StringFilter>;
  ctaText?: InputMaybe<StringFilter>;
};

export type PartsConnectionEdges = {
  __typename?: 'PartsConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Parts>;
};

export type PartsConnection = Connection & {
  __typename?: 'PartsConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<PartsConnectionEdges>>>;
};

export type Mutation = {
  __typename?: 'Mutation';
  addPendingDocument: DocumentNode;
  updateDocument: DocumentNode;
  deleteDocument: DocumentNode;
  createDocument: DocumentNode;
  createFolder: DocumentNode;
  updateGlobal: Global;
  createGlobal: Global;
  updateHome: Home;
  createHome: Home;
  updateBatteries: Batteries;
  createBatteries: Batteries;
  updateService: Service;
  createService: Service;
  updateEquipment: Equipment;
  createEquipment: Equipment;
  updateRacking: Racking;
  createRacking: Racking;
  updateParts: Parts;
  createParts: Parts;
};


export type MutationAddPendingDocumentArgs = {
  collection: Scalars['String']['input'];
  relativePath: Scalars['String']['input'];
  template?: InputMaybe<Scalars['String']['input']>;
};


export type MutationUpdateDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
  params: DocumentUpdateMutation;
};


export type MutationDeleteDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
};


export type MutationCreateDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
  params: DocumentMutation;
};


export type MutationCreateFolderArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
};


export type MutationUpdateGlobalArgs = {
  relativePath: Scalars['String']['input'];
  params: GlobalMutation;
};


export type MutationCreateGlobalArgs = {
  relativePath: Scalars['String']['input'];
  params: GlobalMutation;
};


export type MutationUpdateHomeArgs = {
  relativePath: Scalars['String']['input'];
  params: HomeMutation;
};


export type MutationCreateHomeArgs = {
  relativePath: Scalars['String']['input'];
  params: HomeMutation;
};


export type MutationUpdateBatteriesArgs = {
  relativePath: Scalars['String']['input'];
  params: BatteriesMutation;
};


export type MutationCreateBatteriesArgs = {
  relativePath: Scalars['String']['input'];
  params: BatteriesMutation;
};


export type MutationUpdateServiceArgs = {
  relativePath: Scalars['String']['input'];
  params: ServiceMutation;
};


export type MutationCreateServiceArgs = {
  relativePath: Scalars['String']['input'];
  params: ServiceMutation;
};


export type MutationUpdateEquipmentArgs = {
  relativePath: Scalars['String']['input'];
  params: EquipmentMutation;
};


export type MutationCreateEquipmentArgs = {
  relativePath: Scalars['String']['input'];
  params: EquipmentMutation;
};


export type MutationUpdateRackingArgs = {
  relativePath: Scalars['String']['input'];
  params: RackingMutation;
};


export type MutationCreateRackingArgs = {
  relativePath: Scalars['String']['input'];
  params: RackingMutation;
};


export type MutationUpdatePartsArgs = {
  relativePath: Scalars['String']['input'];
  params: PartsMutation;
};


export type MutationCreatePartsArgs = {
  relativePath: Scalars['String']['input'];
  params: PartsMutation;
};

export type DocumentUpdateMutation = {
  global?: InputMaybe<GlobalMutation>;
  home?: InputMaybe<HomeMutation>;
  batteries?: InputMaybe<BatteriesMutation>;
  service?: InputMaybe<ServiceMutation>;
  equipment?: InputMaybe<EquipmentMutation>;
  racking?: InputMaybe<RackingMutation>;
  parts?: InputMaybe<PartsMutation>;
  relativePath?: InputMaybe<Scalars['String']['input']>;
};

export type DocumentMutation = {
  global?: InputMaybe<GlobalMutation>;
  home?: InputMaybe<HomeMutation>;
  batteries?: InputMaybe<BatteriesMutation>;
  service?: InputMaybe<ServiceMutation>;
  equipment?: InputMaybe<EquipmentMutation>;
  racking?: InputMaybe<RackingMutation>;
  parts?: InputMaybe<PartsMutation>;
};

export type GlobalMutation = {
  companyName?: InputMaybe<Scalars['String']['input']>;
  phone?: InputMaybe<Scalars['String']['input']>;
  email?: InputMaybe<Scalars['String']['input']>;
  address?: InputMaybe<Scalars['String']['input']>;
  hours?: InputMaybe<Scalars['String']['input']>;
};

export type HomeHeroStatsMutation = {
  value?: InputMaybe<Scalars['String']['input']>;
  label?: InputMaybe<Scalars['String']['input']>;
};

export type HomeServicesMutation = {
  badge?: InputMaybe<Scalars['String']['input']>;
  title?: InputMaybe<Scalars['String']['input']>;
  description?: InputMaybe<Scalars['String']['input']>;
  link?: InputMaybe<Scalars['String']['input']>;
};

export type HomeWhyUsMutation = {
  title?: InputMaybe<Scalars['String']['input']>;
  description?: InputMaybe<Scalars['String']['input']>;
};

export type HomeMutation = {
  seoTitle?: InputMaybe<Scalars['String']['input']>;
  seoDescription?: InputMaybe<Scalars['String']['input']>;
  heroBadge?: InputMaybe<Scalars['String']['input']>;
  heroTitle?: InputMaybe<Scalars['String']['input']>;
  heroHighlight?: InputMaybe<Scalars['String']['input']>;
  heroDescription?: InputMaybe<Scalars['String']['input']>;
  heroCta1Text?: InputMaybe<Scalars['String']['input']>;
  heroCta1Link?: InputMaybe<Scalars['String']['input']>;
  heroCta2Text?: InputMaybe<Scalars['String']['input']>;
  heroCta2Link?: InputMaybe<Scalars['String']['input']>;
  heroStats?: InputMaybe<Array<InputMaybe<HomeHeroStatsMutation>>>;
  services?: InputMaybe<Array<InputMaybe<HomeServicesMutation>>>;
  batterySplitImage?: InputMaybe<Scalars['String']['input']>;
  batterySplitHeading?: InputMaybe<Scalars['String']['input']>;
  batterySplitText?: InputMaybe<Scalars['String']['input']>;
  batterySplitCtaText?: InputMaybe<Scalars['String']['input']>;
  batterySplitCtaLink?: InputMaybe<Scalars['String']['input']>;
  whyUs?: InputMaybe<Array<InputMaybe<HomeWhyUsMutation>>>;
  equipmentSplitImage?: InputMaybe<Scalars['String']['input']>;
  equipmentSplitHeading?: InputMaybe<Scalars['String']['input']>;
  equipmentSplitText?: InputMaybe<Scalars['String']['input']>;
  equipmentSplitCtaText?: InputMaybe<Scalars['String']['input']>;
  equipmentSplitCtaLink?: InputMaybe<Scalars['String']['input']>;
  bannerImage?: InputMaybe<Scalars['String']['input']>;
  bannerHeading?: InputMaybe<Scalars['String']['input']>;
  bannerText?: InputMaybe<Scalars['String']['input']>;
  ctaHeading?: InputMaybe<Scalars['String']['input']>;
  ctaText?: InputMaybe<Scalars['String']['input']>;
  ctaCta1Text?: InputMaybe<Scalars['String']['input']>;
  ctaCta1Link?: InputMaybe<Scalars['String']['input']>;
  ctaCta2Text?: InputMaybe<Scalars['String']['input']>;
  ctaCta2Link?: InputMaybe<Scalars['String']['input']>;
};

export type BatteriesLithiumCardsMutation = {
  badge?: InputMaybe<Scalars['String']['input']>;
  title?: InputMaybe<Scalars['String']['input']>;
  description?: InputMaybe<Scalars['String']['input']>;
};

export type BatteriesRejuvCardsMutation = {
  title?: InputMaybe<Scalars['String']['input']>;
  description?: InputMaybe<Scalars['String']['input']>;
};

export type BatteriesEquipCardsMutation = {
  title?: InputMaybe<Scalars['String']['input']>;
  description?: InputMaybe<Scalars['String']['input']>;
};

export type BatteriesMutation = {
  seoTitle?: InputMaybe<Scalars['String']['input']>;
  seoDescription?: InputMaybe<Scalars['String']['input']>;
  heroBadge?: InputMaybe<Scalars['String']['input']>;
  heroTitle?: InputMaybe<Scalars['String']['input']>;
  heroHighlight?: InputMaybe<Scalars['String']['input']>;
  heroDescription?: InputMaybe<Scalars['String']['input']>;
  heroCta1Text?: InputMaybe<Scalars['String']['input']>;
  heroCta1Link?: InputMaybe<Scalars['String']['input']>;
  heroCta2Text?: InputMaybe<Scalars['String']['input']>;
  heroCta2Link?: InputMaybe<Scalars['String']['input']>;
  lithiumHeading?: InputMaybe<Scalars['String']['input']>;
  lithiumSubtitle?: InputMaybe<Scalars['String']['input']>;
  lithiumCards?: InputMaybe<Array<InputMaybe<BatteriesLithiumCardsMutation>>>;
  splitImage?: InputMaybe<Scalars['String']['input']>;
  splitHeading?: InputMaybe<Scalars['String']['input']>;
  splitText?: InputMaybe<Scalars['String']['input']>;
  splitCtaText?: InputMaybe<Scalars['String']['input']>;
  splitCtaLink?: InputMaybe<Scalars['String']['input']>;
  rejuvHeading?: InputMaybe<Scalars['String']['input']>;
  rejuvSubtitle?: InputMaybe<Scalars['String']['input']>;
  rejuvCards?: InputMaybe<Array<InputMaybe<BatteriesRejuvCardsMutation>>>;
  rejuvCtaText?: InputMaybe<Scalars['String']['input']>;
  rejuvCtaLink?: InputMaybe<Scalars['String']['input']>;
  equipHeading?: InputMaybe<Scalars['String']['input']>;
  equipSubtitle?: InputMaybe<Scalars['String']['input']>;
  equipCards?: InputMaybe<Array<InputMaybe<BatteriesEquipCardsMutation>>>;
  ctaHeading?: InputMaybe<Scalars['String']['input']>;
  ctaText?: InputMaybe<Scalars['String']['input']>;
};

export type ServiceServiceCardsMutation = {
  badge?: InputMaybe<Scalars['String']['input']>;
  title?: InputMaybe<Scalars['String']['input']>;
  description?: InputMaybe<Scalars['String']['input']>;
};

export type ServiceEquipCardsMutation = {
  title?: InputMaybe<Scalars['String']['input']>;
  description?: InputMaybe<Scalars['String']['input']>;
};

export type ServiceMutation = {
  seoTitle?: InputMaybe<Scalars['String']['input']>;
  seoDescription?: InputMaybe<Scalars['String']['input']>;
  heroBadge?: InputMaybe<Scalars['String']['input']>;
  heroTitle?: InputMaybe<Scalars['String']['input']>;
  heroHighlight?: InputMaybe<Scalars['String']['input']>;
  heroDescription?: InputMaybe<Scalars['String']['input']>;
  heroCta1Text?: InputMaybe<Scalars['String']['input']>;
  heroCta1Link?: InputMaybe<Scalars['String']['input']>;
  heroCta2Text?: InputMaybe<Scalars['String']['input']>;
  heroCta2Link?: InputMaybe<Scalars['String']['input']>;
  serviceCards?: InputMaybe<Array<InputMaybe<ServiceServiceCardsMutation>>>;
  bannerImage?: InputMaybe<Scalars['String']['input']>;
  bannerHeading?: InputMaybe<Scalars['String']['input']>;
  bannerText?: InputMaybe<Scalars['String']['input']>;
  equipHeading?: InputMaybe<Scalars['String']['input']>;
  equipSubtitle?: InputMaybe<Scalars['String']['input']>;
  equipCards?: InputMaybe<Array<InputMaybe<ServiceEquipCardsMutation>>>;
  ctaHeading?: InputMaybe<Scalars['String']['input']>;
  ctaText?: InputMaybe<Scalars['String']['input']>;
};

export type EquipmentEquipCardsMutation = {
  badge?: InputMaybe<Scalars['String']['input']>;
  title?: InputMaybe<Scalars['String']['input']>;
  description?: InputMaybe<Scalars['String']['input']>;
};

export type EquipmentWhyBuyCardsMutation = {
  title?: InputMaybe<Scalars['String']['input']>;
  description?: InputMaybe<Scalars['String']['input']>;
};

export type EquipmentMutation = {
  seoTitle?: InputMaybe<Scalars['String']['input']>;
  seoDescription?: InputMaybe<Scalars['String']['input']>;
  heroBadge?: InputMaybe<Scalars['String']['input']>;
  heroTitle?: InputMaybe<Scalars['String']['input']>;
  heroHighlight?: InputMaybe<Scalars['String']['input']>;
  heroDescription?: InputMaybe<Scalars['String']['input']>;
  heroCta1Text?: InputMaybe<Scalars['String']['input']>;
  heroCta1Link?: InputMaybe<Scalars['String']['input']>;
  heroCta2Text?: InputMaybe<Scalars['String']['input']>;
  heroCta2Link?: InputMaybe<Scalars['String']['input']>;
  equipCards?: InputMaybe<Array<InputMaybe<EquipmentEquipCardsMutation>>>;
  bannerImage?: InputMaybe<Scalars['String']['input']>;
  bannerHeading?: InputMaybe<Scalars['String']['input']>;
  bannerText?: InputMaybe<Scalars['String']['input']>;
  inventoryHeading?: InputMaybe<Scalars['String']['input']>;
  inventorySubtitle?: InputMaybe<Scalars['String']['input']>;
  inventoryPlaceholder?: InputMaybe<Scalars['String']['input']>;
  whyBuyCards?: InputMaybe<Array<InputMaybe<EquipmentWhyBuyCardsMutation>>>;
  ctaHeading?: InputMaybe<Scalars['String']['input']>;
  ctaText?: InputMaybe<Scalars['String']['input']>;
};

export type RackingRackingCardsMutation = {
  badge?: InputMaybe<Scalars['String']['input']>;
  title?: InputMaybe<Scalars['String']['input']>;
  description?: InputMaybe<Scalars['String']['input']>;
};

export type RackingDockCardsMutation = {
  title?: InputMaybe<Scalars['String']['input']>;
  description?: InputMaybe<Scalars['String']['input']>;
};

export type RackingMutation = {
  seoTitle?: InputMaybe<Scalars['String']['input']>;
  seoDescription?: InputMaybe<Scalars['String']['input']>;
  heroBadge?: InputMaybe<Scalars['String']['input']>;
  heroTitle?: InputMaybe<Scalars['String']['input']>;
  heroHighlight?: InputMaybe<Scalars['String']['input']>;
  heroDescription?: InputMaybe<Scalars['String']['input']>;
  heroCta1Text?: InputMaybe<Scalars['String']['input']>;
  heroCta1Link?: InputMaybe<Scalars['String']['input']>;
  rackingHeading?: InputMaybe<Scalars['String']['input']>;
  rackingSubtitle?: InputMaybe<Scalars['String']['input']>;
  rackingCards?: InputMaybe<Array<InputMaybe<RackingRackingCardsMutation>>>;
  bannerImage?: InputMaybe<Scalars['String']['input']>;
  bannerHeading?: InputMaybe<Scalars['String']['input']>;
  bannerText?: InputMaybe<Scalars['String']['input']>;
  dockHeading?: InputMaybe<Scalars['String']['input']>;
  dockSubtitle?: InputMaybe<Scalars['String']['input']>;
  dockCards?: InputMaybe<Array<InputMaybe<RackingDockCardsMutation>>>;
  ctaHeading?: InputMaybe<Scalars['String']['input']>;
  ctaText?: InputMaybe<Scalars['String']['input']>;
};

export type PartsFeatureCardsMutation = {
  badge?: InputMaybe<Scalars['String']['input']>;
  title?: InputMaybe<Scalars['String']['input']>;
  description?: InputMaybe<Scalars['String']['input']>;
};

export type PartsMutation = {
  seoTitle?: InputMaybe<Scalars['String']['input']>;
  seoDescription?: InputMaybe<Scalars['String']['input']>;
  heroBadge?: InputMaybe<Scalars['String']['input']>;
  heroTitle?: InputMaybe<Scalars['String']['input']>;
  heroHighlight?: InputMaybe<Scalars['String']['input']>;
  heroDescription?: InputMaybe<Scalars['String']['input']>;
  heroCta1Text?: InputMaybe<Scalars['String']['input']>;
  heroCta1Link?: InputMaybe<Scalars['String']['input']>;
  featureCards?: InputMaybe<Array<InputMaybe<PartsFeatureCardsMutation>>>;
  ctaHeading?: InputMaybe<Scalars['String']['input']>;
  ctaText?: InputMaybe<Scalars['String']['input']>;
};

export type GlobalPartsFragment = { __typename: 'Global', companyName: string, phone: string, email: string, address?: string | null, hours?: string | null };

export type HomePartsFragment = { __typename: 'Home', seoTitle: string, seoDescription?: string | null, heroBadge?: string | null, heroTitle: string, heroHighlight?: string | null, heroDescription?: string | null, heroCta1Text?: string | null, heroCta1Link?: string | null, heroCta2Text?: string | null, heroCta2Link?: string | null, batterySplitImage?: string | null, batterySplitHeading?: string | null, batterySplitText?: string | null, batterySplitCtaText?: string | null, batterySplitCtaLink?: string | null, equipmentSplitImage?: string | null, equipmentSplitHeading?: string | null, equipmentSplitText?: string | null, equipmentSplitCtaText?: string | null, equipmentSplitCtaLink?: string | null, bannerImage?: string | null, bannerHeading?: string | null, bannerText?: string | null, ctaHeading?: string | null, ctaText?: string | null, ctaCta1Text?: string | null, ctaCta1Link?: string | null, ctaCta2Text?: string | null, ctaCta2Link?: string | null, heroStats?: Array<{ __typename: 'HomeHeroStats', value?: string | null, label?: string | null } | null> | null, services?: Array<{ __typename: 'HomeServices', badge?: string | null, title: string, description?: string | null, link?: string | null } | null> | null, whyUs?: Array<{ __typename: 'HomeWhyUs', title: string, description?: string | null } | null> | null };

export type BatteriesPartsFragment = { __typename: 'Batteries', seoTitle: string, seoDescription?: string | null, heroBadge?: string | null, heroTitle?: string | null, heroHighlight?: string | null, heroDescription?: string | null, heroCta1Text?: string | null, heroCta1Link?: string | null, heroCta2Text?: string | null, heroCta2Link?: string | null, lithiumHeading?: string | null, lithiumSubtitle?: string | null, splitImage?: string | null, splitHeading?: string | null, splitText?: string | null, splitCtaText?: string | null, splitCtaLink?: string | null, rejuvHeading?: string | null, rejuvSubtitle?: string | null, rejuvCtaText?: string | null, rejuvCtaLink?: string | null, equipHeading?: string | null, equipSubtitle?: string | null, ctaHeading?: string | null, ctaText?: string | null, lithiumCards?: Array<{ __typename: 'BatteriesLithiumCards', badge?: string | null, title: string, description?: string | null } | null> | null, rejuvCards?: Array<{ __typename: 'BatteriesRejuvCards', title: string, description?: string | null } | null> | null, equipCards?: Array<{ __typename: 'BatteriesEquipCards', title: string, description?: string | null } | null> | null };

export type ServicePartsFragment = { __typename: 'Service', seoTitle: string, seoDescription?: string | null, heroBadge?: string | null, heroTitle?: string | null, heroHighlight?: string | null, heroDescription?: string | null, heroCta1Text?: string | null, heroCta1Link?: string | null, heroCta2Text?: string | null, heroCta2Link?: string | null, bannerImage?: string | null, bannerHeading?: string | null, bannerText?: string | null, equipHeading?: string | null, equipSubtitle?: string | null, ctaHeading?: string | null, ctaText?: string | null, serviceCards?: Array<{ __typename: 'ServiceServiceCards', badge?: string | null, title: string, description?: string | null } | null> | null, equipCards?: Array<{ __typename: 'ServiceEquipCards', title: string, description?: string | null } | null> | null };

export type EquipmentPartsFragment = { __typename: 'Equipment', seoTitle: string, seoDescription?: string | null, heroBadge?: string | null, heroTitle?: string | null, heroHighlight?: string | null, heroDescription?: string | null, heroCta1Text?: string | null, heroCta1Link?: string | null, heroCta2Text?: string | null, heroCta2Link?: string | null, bannerImage?: string | null, bannerHeading?: string | null, bannerText?: string | null, inventoryHeading?: string | null, inventorySubtitle?: string | null, inventoryPlaceholder?: string | null, ctaHeading?: string | null, ctaText?: string | null, equipCards?: Array<{ __typename: 'EquipmentEquipCards', badge?: string | null, title: string, description?: string | null } | null> | null, whyBuyCards?: Array<{ __typename: 'EquipmentWhyBuyCards', title: string, description?: string | null } | null> | null };

export type RackingPartsFragment = { __typename: 'Racking', seoTitle: string, seoDescription?: string | null, heroBadge?: string | null, heroTitle?: string | null, heroHighlight?: string | null, heroDescription?: string | null, heroCta1Text?: string | null, heroCta1Link?: string | null, rackingHeading?: string | null, rackingSubtitle?: string | null, bannerImage?: string | null, bannerHeading?: string | null, bannerText?: string | null, dockHeading?: string | null, dockSubtitle?: string | null, ctaHeading?: string | null, ctaText?: string | null, rackingCards?: Array<{ __typename: 'RackingRackingCards', badge?: string | null, title: string, description?: string | null } | null> | null, dockCards?: Array<{ __typename: 'RackingDockCards', title: string, description?: string | null } | null> | null };

export type PartsPartsFragment = { __typename: 'Parts', seoTitle: string, seoDescription?: string | null, heroBadge?: string | null, heroTitle?: string | null, heroHighlight?: string | null, heroDescription?: string | null, heroCta1Text?: string | null, heroCta1Link?: string | null, ctaHeading?: string | null, ctaText?: string | null, featureCards?: Array<{ __typename: 'PartsFeatureCards', badge?: string | null, title: string, description?: string | null } | null> | null };

export type GlobalQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type GlobalQuery = { __typename?: 'Query', global: { __typename: 'Global', id: string, companyName: string, phone: string, email: string, address?: string | null, hours?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } };

export type GlobalConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<GlobalFilter>;
}>;


export type GlobalConnectionQuery = { __typename?: 'Query', globalConnection: { __typename?: 'GlobalConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'GlobalConnectionEdges', cursor: string, node?: { __typename: 'Global', id: string, companyName: string, phone: string, email: string, address?: string | null, hours?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } | null } | null> | null } };

export type HomeQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type HomeQuery = { __typename?: 'Query', home: { __typename: 'Home', id: string, seoTitle: string, seoDescription?: string | null, heroBadge?: string | null, heroTitle: string, heroHighlight?: string | null, heroDescription?: string | null, heroCta1Text?: string | null, heroCta1Link?: string | null, heroCta2Text?: string | null, heroCta2Link?: string | null, batterySplitImage?: string | null, batterySplitHeading?: string | null, batterySplitText?: string | null, batterySplitCtaText?: string | null, batterySplitCtaLink?: string | null, equipmentSplitImage?: string | null, equipmentSplitHeading?: string | null, equipmentSplitText?: string | null, equipmentSplitCtaText?: string | null, equipmentSplitCtaLink?: string | null, bannerImage?: string | null, bannerHeading?: string | null, bannerText?: string | null, ctaHeading?: string | null, ctaText?: string | null, ctaCta1Text?: string | null, ctaCta1Link?: string | null, ctaCta2Text?: string | null, ctaCta2Link?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, heroStats?: Array<{ __typename: 'HomeHeroStats', value?: string | null, label?: string | null } | null> | null, services?: Array<{ __typename: 'HomeServices', badge?: string | null, title: string, description?: string | null, link?: string | null } | null> | null, whyUs?: Array<{ __typename: 'HomeWhyUs', title: string, description?: string | null } | null> | null } };

export type HomeConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<HomeFilter>;
}>;


export type HomeConnectionQuery = { __typename?: 'Query', homeConnection: { __typename?: 'HomeConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'HomeConnectionEdges', cursor: string, node?: { __typename: 'Home', id: string, seoTitle: string, seoDescription?: string | null, heroBadge?: string | null, heroTitle: string, heroHighlight?: string | null, heroDescription?: string | null, heroCta1Text?: string | null, heroCta1Link?: string | null, heroCta2Text?: string | null, heroCta2Link?: string | null, batterySplitImage?: string | null, batterySplitHeading?: string | null, batterySplitText?: string | null, batterySplitCtaText?: string | null, batterySplitCtaLink?: string | null, equipmentSplitImage?: string | null, equipmentSplitHeading?: string | null, equipmentSplitText?: string | null, equipmentSplitCtaText?: string | null, equipmentSplitCtaLink?: string | null, bannerImage?: string | null, bannerHeading?: string | null, bannerText?: string | null, ctaHeading?: string | null, ctaText?: string | null, ctaCta1Text?: string | null, ctaCta1Link?: string | null, ctaCta2Text?: string | null, ctaCta2Link?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, heroStats?: Array<{ __typename: 'HomeHeroStats', value?: string | null, label?: string | null } | null> | null, services?: Array<{ __typename: 'HomeServices', badge?: string | null, title: string, description?: string | null, link?: string | null } | null> | null, whyUs?: Array<{ __typename: 'HomeWhyUs', title: string, description?: string | null } | null> | null } | null } | null> | null } };

export type BatteriesQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type BatteriesQuery = { __typename?: 'Query', batteries: { __typename: 'Batteries', id: string, seoTitle: string, seoDescription?: string | null, heroBadge?: string | null, heroTitle?: string | null, heroHighlight?: string | null, heroDescription?: string | null, heroCta1Text?: string | null, heroCta1Link?: string | null, heroCta2Text?: string | null, heroCta2Link?: string | null, lithiumHeading?: string | null, lithiumSubtitle?: string | null, splitImage?: string | null, splitHeading?: string | null, splitText?: string | null, splitCtaText?: string | null, splitCtaLink?: string | null, rejuvHeading?: string | null, rejuvSubtitle?: string | null, rejuvCtaText?: string | null, rejuvCtaLink?: string | null, equipHeading?: string | null, equipSubtitle?: string | null, ctaHeading?: string | null, ctaText?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, lithiumCards?: Array<{ __typename: 'BatteriesLithiumCards', badge?: string | null, title: string, description?: string | null } | null> | null, rejuvCards?: Array<{ __typename: 'BatteriesRejuvCards', title: string, description?: string | null } | null> | null, equipCards?: Array<{ __typename: 'BatteriesEquipCards', title: string, description?: string | null } | null> | null } };

export type BatteriesConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<BatteriesFilter>;
}>;


export type BatteriesConnectionQuery = { __typename?: 'Query', batteriesConnection: { __typename?: 'BatteriesConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'BatteriesConnectionEdges', cursor: string, node?: { __typename: 'Batteries', id: string, seoTitle: string, seoDescription?: string | null, heroBadge?: string | null, heroTitle?: string | null, heroHighlight?: string | null, heroDescription?: string | null, heroCta1Text?: string | null, heroCta1Link?: string | null, heroCta2Text?: string | null, heroCta2Link?: string | null, lithiumHeading?: string | null, lithiumSubtitle?: string | null, splitImage?: string | null, splitHeading?: string | null, splitText?: string | null, splitCtaText?: string | null, splitCtaLink?: string | null, rejuvHeading?: string | null, rejuvSubtitle?: string | null, rejuvCtaText?: string | null, rejuvCtaLink?: string | null, equipHeading?: string | null, equipSubtitle?: string | null, ctaHeading?: string | null, ctaText?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, lithiumCards?: Array<{ __typename: 'BatteriesLithiumCards', badge?: string | null, title: string, description?: string | null } | null> | null, rejuvCards?: Array<{ __typename: 'BatteriesRejuvCards', title: string, description?: string | null } | null> | null, equipCards?: Array<{ __typename: 'BatteriesEquipCards', title: string, description?: string | null } | null> | null } | null } | null> | null } };

export type ServiceQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type ServiceQuery = { __typename?: 'Query', service: { __typename: 'Service', id: string, seoTitle: string, seoDescription?: string | null, heroBadge?: string | null, heroTitle?: string | null, heroHighlight?: string | null, heroDescription?: string | null, heroCta1Text?: string | null, heroCta1Link?: string | null, heroCta2Text?: string | null, heroCta2Link?: string | null, bannerImage?: string | null, bannerHeading?: string | null, bannerText?: string | null, equipHeading?: string | null, equipSubtitle?: string | null, ctaHeading?: string | null, ctaText?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, serviceCards?: Array<{ __typename: 'ServiceServiceCards', badge?: string | null, title: string, description?: string | null } | null> | null, equipCards?: Array<{ __typename: 'ServiceEquipCards', title: string, description?: string | null } | null> | null } };

export type ServiceConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<ServiceFilter>;
}>;


export type ServiceConnectionQuery = { __typename?: 'Query', serviceConnection: { __typename?: 'ServiceConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'ServiceConnectionEdges', cursor: string, node?: { __typename: 'Service', id: string, seoTitle: string, seoDescription?: string | null, heroBadge?: string | null, heroTitle?: string | null, heroHighlight?: string | null, heroDescription?: string | null, heroCta1Text?: string | null, heroCta1Link?: string | null, heroCta2Text?: string | null, heroCta2Link?: string | null, bannerImage?: string | null, bannerHeading?: string | null, bannerText?: string | null, equipHeading?: string | null, equipSubtitle?: string | null, ctaHeading?: string | null, ctaText?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, serviceCards?: Array<{ __typename: 'ServiceServiceCards', badge?: string | null, title: string, description?: string | null } | null> | null, equipCards?: Array<{ __typename: 'ServiceEquipCards', title: string, description?: string | null } | null> | null } | null } | null> | null } };

export type EquipmentQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type EquipmentQuery = { __typename?: 'Query', equipment: { __typename: 'Equipment', id: string, seoTitle: string, seoDescription?: string | null, heroBadge?: string | null, heroTitle?: string | null, heroHighlight?: string | null, heroDescription?: string | null, heroCta1Text?: string | null, heroCta1Link?: string | null, heroCta2Text?: string | null, heroCta2Link?: string | null, bannerImage?: string | null, bannerHeading?: string | null, bannerText?: string | null, inventoryHeading?: string | null, inventorySubtitle?: string | null, inventoryPlaceholder?: string | null, ctaHeading?: string | null, ctaText?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, equipCards?: Array<{ __typename: 'EquipmentEquipCards', badge?: string | null, title: string, description?: string | null } | null> | null, whyBuyCards?: Array<{ __typename: 'EquipmentWhyBuyCards', title: string, description?: string | null } | null> | null } };

export type EquipmentConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<EquipmentFilter>;
}>;


export type EquipmentConnectionQuery = { __typename?: 'Query', equipmentConnection: { __typename?: 'EquipmentConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'EquipmentConnectionEdges', cursor: string, node?: { __typename: 'Equipment', id: string, seoTitle: string, seoDescription?: string | null, heroBadge?: string | null, heroTitle?: string | null, heroHighlight?: string | null, heroDescription?: string | null, heroCta1Text?: string | null, heroCta1Link?: string | null, heroCta2Text?: string | null, heroCta2Link?: string | null, bannerImage?: string | null, bannerHeading?: string | null, bannerText?: string | null, inventoryHeading?: string | null, inventorySubtitle?: string | null, inventoryPlaceholder?: string | null, ctaHeading?: string | null, ctaText?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, equipCards?: Array<{ __typename: 'EquipmentEquipCards', badge?: string | null, title: string, description?: string | null } | null> | null, whyBuyCards?: Array<{ __typename: 'EquipmentWhyBuyCards', title: string, description?: string | null } | null> | null } | null } | null> | null } };

export type RackingQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type RackingQuery = { __typename?: 'Query', racking: { __typename: 'Racking', id: string, seoTitle: string, seoDescription?: string | null, heroBadge?: string | null, heroTitle?: string | null, heroHighlight?: string | null, heroDescription?: string | null, heroCta1Text?: string | null, heroCta1Link?: string | null, rackingHeading?: string | null, rackingSubtitle?: string | null, bannerImage?: string | null, bannerHeading?: string | null, bannerText?: string | null, dockHeading?: string | null, dockSubtitle?: string | null, ctaHeading?: string | null, ctaText?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, rackingCards?: Array<{ __typename: 'RackingRackingCards', badge?: string | null, title: string, description?: string | null } | null> | null, dockCards?: Array<{ __typename: 'RackingDockCards', title: string, description?: string | null } | null> | null } };

export type RackingConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<RackingFilter>;
}>;


export type RackingConnectionQuery = { __typename?: 'Query', rackingConnection: { __typename?: 'RackingConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'RackingConnectionEdges', cursor: string, node?: { __typename: 'Racking', id: string, seoTitle: string, seoDescription?: string | null, heroBadge?: string | null, heroTitle?: string | null, heroHighlight?: string | null, heroDescription?: string | null, heroCta1Text?: string | null, heroCta1Link?: string | null, rackingHeading?: string | null, rackingSubtitle?: string | null, bannerImage?: string | null, bannerHeading?: string | null, bannerText?: string | null, dockHeading?: string | null, dockSubtitle?: string | null, ctaHeading?: string | null, ctaText?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, rackingCards?: Array<{ __typename: 'RackingRackingCards', badge?: string | null, title: string, description?: string | null } | null> | null, dockCards?: Array<{ __typename: 'RackingDockCards', title: string, description?: string | null } | null> | null } | null } | null> | null } };

export type PartsQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type PartsQuery = { __typename?: 'Query', parts: { __typename: 'Parts', id: string, seoTitle: string, seoDescription?: string | null, heroBadge?: string | null, heroTitle?: string | null, heroHighlight?: string | null, heroDescription?: string | null, heroCta1Text?: string | null, heroCta1Link?: string | null, ctaHeading?: string | null, ctaText?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, featureCards?: Array<{ __typename: 'PartsFeatureCards', badge?: string | null, title: string, description?: string | null } | null> | null } };

export type PartsConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<PartsFilter>;
}>;


export type PartsConnectionQuery = { __typename?: 'Query', partsConnection: { __typename?: 'PartsConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'PartsConnectionEdges', cursor: string, node?: { __typename: 'Parts', id: string, seoTitle: string, seoDescription?: string | null, heroBadge?: string | null, heroTitle?: string | null, heroHighlight?: string | null, heroDescription?: string | null, heroCta1Text?: string | null, heroCta1Link?: string | null, ctaHeading?: string | null, ctaText?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, featureCards?: Array<{ __typename: 'PartsFeatureCards', badge?: string | null, title: string, description?: string | null } | null> | null } | null } | null> | null } };

export const GlobalPartsFragmentDoc = gql`
    fragment GlobalParts on Global {
  __typename
  companyName
  phone
  email
  address
  hours
}
    `;
export const HomePartsFragmentDoc = gql`
    fragment HomeParts on Home {
  __typename
  seoTitle
  seoDescription
  heroBadge
  heroTitle
  heroHighlight
  heroDescription
  heroCta1Text
  heroCta1Link
  heroCta2Text
  heroCta2Link
  heroStats {
    __typename
    value
    label
  }
  services {
    __typename
    badge
    title
    description
    link
  }
  batterySplitImage
  batterySplitHeading
  batterySplitText
  batterySplitCtaText
  batterySplitCtaLink
  whyUs {
    __typename
    title
    description
  }
  equipmentSplitImage
  equipmentSplitHeading
  equipmentSplitText
  equipmentSplitCtaText
  equipmentSplitCtaLink
  bannerImage
  bannerHeading
  bannerText
  ctaHeading
  ctaText
  ctaCta1Text
  ctaCta1Link
  ctaCta2Text
  ctaCta2Link
}
    `;
export const BatteriesPartsFragmentDoc = gql`
    fragment BatteriesParts on Batteries {
  __typename
  seoTitle
  seoDescription
  heroBadge
  heroTitle
  heroHighlight
  heroDescription
  heroCta1Text
  heroCta1Link
  heroCta2Text
  heroCta2Link
  lithiumHeading
  lithiumSubtitle
  lithiumCards {
    __typename
    badge
    title
    description
  }
  splitImage
  splitHeading
  splitText
  splitCtaText
  splitCtaLink
  rejuvHeading
  rejuvSubtitle
  rejuvCards {
    __typename
    title
    description
  }
  rejuvCtaText
  rejuvCtaLink
  equipHeading
  equipSubtitle
  equipCards {
    __typename
    title
    description
  }
  ctaHeading
  ctaText
}
    `;
export const ServicePartsFragmentDoc = gql`
    fragment ServiceParts on Service {
  __typename
  seoTitle
  seoDescription
  heroBadge
  heroTitle
  heroHighlight
  heroDescription
  heroCta1Text
  heroCta1Link
  heroCta2Text
  heroCta2Link
  serviceCards {
    __typename
    badge
    title
    description
  }
  bannerImage
  bannerHeading
  bannerText
  equipHeading
  equipSubtitle
  equipCards {
    __typename
    title
    description
  }
  ctaHeading
  ctaText
}
    `;
export const EquipmentPartsFragmentDoc = gql`
    fragment EquipmentParts on Equipment {
  __typename
  seoTitle
  seoDescription
  heroBadge
  heroTitle
  heroHighlight
  heroDescription
  heroCta1Text
  heroCta1Link
  heroCta2Text
  heroCta2Link
  equipCards {
    __typename
    badge
    title
    description
  }
  bannerImage
  bannerHeading
  bannerText
  inventoryHeading
  inventorySubtitle
  inventoryPlaceholder
  whyBuyCards {
    __typename
    title
    description
  }
  ctaHeading
  ctaText
}
    `;
export const RackingPartsFragmentDoc = gql`
    fragment RackingParts on Racking {
  __typename
  seoTitle
  seoDescription
  heroBadge
  heroTitle
  heroHighlight
  heroDescription
  heroCta1Text
  heroCta1Link
  rackingHeading
  rackingSubtitle
  rackingCards {
    __typename
    badge
    title
    description
  }
  bannerImage
  bannerHeading
  bannerText
  dockHeading
  dockSubtitle
  dockCards {
    __typename
    title
    description
  }
  ctaHeading
  ctaText
}
    `;
export const PartsPartsFragmentDoc = gql`
    fragment PartsParts on Parts {
  __typename
  seoTitle
  seoDescription
  heroBadge
  heroTitle
  heroHighlight
  heroDescription
  heroCta1Text
  heroCta1Link
  featureCards {
    __typename
    badge
    title
    description
  }
  ctaHeading
  ctaText
}
    `;
export const GlobalDocument = gql`
    query global($relativePath: String!) {
  global(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...GlobalParts
  }
}
    ${GlobalPartsFragmentDoc}`;
export const GlobalConnectionDocument = gql`
    query globalConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: GlobalFilter) {
  globalConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...GlobalParts
      }
    }
  }
}
    ${GlobalPartsFragmentDoc}`;
export const HomeDocument = gql`
    query home($relativePath: String!) {
  home(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...HomeParts
  }
}
    ${HomePartsFragmentDoc}`;
export const HomeConnectionDocument = gql`
    query homeConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: HomeFilter) {
  homeConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...HomeParts
      }
    }
  }
}
    ${HomePartsFragmentDoc}`;
export const BatteriesDocument = gql`
    query batteries($relativePath: String!) {
  batteries(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...BatteriesParts
  }
}
    ${BatteriesPartsFragmentDoc}`;
export const BatteriesConnectionDocument = gql`
    query batteriesConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: BatteriesFilter) {
  batteriesConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...BatteriesParts
      }
    }
  }
}
    ${BatteriesPartsFragmentDoc}`;
export const ServiceDocument = gql`
    query service($relativePath: String!) {
  service(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...ServiceParts
  }
}
    ${ServicePartsFragmentDoc}`;
export const ServiceConnectionDocument = gql`
    query serviceConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: ServiceFilter) {
  serviceConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...ServiceParts
      }
    }
  }
}
    ${ServicePartsFragmentDoc}`;
export const EquipmentDocument = gql`
    query equipment($relativePath: String!) {
  equipment(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...EquipmentParts
  }
}
    ${EquipmentPartsFragmentDoc}`;
export const EquipmentConnectionDocument = gql`
    query equipmentConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: EquipmentFilter) {
  equipmentConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...EquipmentParts
      }
    }
  }
}
    ${EquipmentPartsFragmentDoc}`;
export const RackingDocument = gql`
    query racking($relativePath: String!) {
  racking(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...RackingParts
  }
}
    ${RackingPartsFragmentDoc}`;
export const RackingConnectionDocument = gql`
    query rackingConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: RackingFilter) {
  rackingConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...RackingParts
      }
    }
  }
}
    ${RackingPartsFragmentDoc}`;
export const PartsDocument = gql`
    query parts($relativePath: String!) {
  parts(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...PartsParts
  }
}
    ${PartsPartsFragmentDoc}`;
export const PartsConnectionDocument = gql`
    query partsConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: PartsFilter) {
  partsConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...PartsParts
      }
    }
  }
}
    ${PartsPartsFragmentDoc}`;
export type Requester<C= {}> = <R, V>(doc: DocumentNode, vars?: V, options?: C) => Promise<R>
  export function getSdk<C>(requester: Requester<C>) {
    return {
      global(variables: GlobalQueryVariables, options?: C): Promise<{data: GlobalQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: GlobalQueryVariables, query: string}> {
        return requester<{data: GlobalQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: GlobalQueryVariables, query: string}, GlobalQueryVariables>(GlobalDocument, variables, options);
      },
    globalConnection(variables?: GlobalConnectionQueryVariables, options?: C): Promise<{data: GlobalConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: GlobalConnectionQueryVariables, query: string}> {
        return requester<{data: GlobalConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: GlobalConnectionQueryVariables, query: string}, GlobalConnectionQueryVariables>(GlobalConnectionDocument, variables, options);
      },
    home(variables: HomeQueryVariables, options?: C): Promise<{data: HomeQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: HomeQueryVariables, query: string}> {
        return requester<{data: HomeQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: HomeQueryVariables, query: string}, HomeQueryVariables>(HomeDocument, variables, options);
      },
    homeConnection(variables?: HomeConnectionQueryVariables, options?: C): Promise<{data: HomeConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: HomeConnectionQueryVariables, query: string}> {
        return requester<{data: HomeConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: HomeConnectionQueryVariables, query: string}, HomeConnectionQueryVariables>(HomeConnectionDocument, variables, options);
      },
    batteries(variables: BatteriesQueryVariables, options?: C): Promise<{data: BatteriesQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: BatteriesQueryVariables, query: string}> {
        return requester<{data: BatteriesQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: BatteriesQueryVariables, query: string}, BatteriesQueryVariables>(BatteriesDocument, variables, options);
      },
    batteriesConnection(variables?: BatteriesConnectionQueryVariables, options?: C): Promise<{data: BatteriesConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: BatteriesConnectionQueryVariables, query: string}> {
        return requester<{data: BatteriesConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: BatteriesConnectionQueryVariables, query: string}, BatteriesConnectionQueryVariables>(BatteriesConnectionDocument, variables, options);
      },
    service(variables: ServiceQueryVariables, options?: C): Promise<{data: ServiceQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ServiceQueryVariables, query: string}> {
        return requester<{data: ServiceQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ServiceQueryVariables, query: string}, ServiceQueryVariables>(ServiceDocument, variables, options);
      },
    serviceConnection(variables?: ServiceConnectionQueryVariables, options?: C): Promise<{data: ServiceConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ServiceConnectionQueryVariables, query: string}> {
        return requester<{data: ServiceConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ServiceConnectionQueryVariables, query: string}, ServiceConnectionQueryVariables>(ServiceConnectionDocument, variables, options);
      },
    equipment(variables: EquipmentQueryVariables, options?: C): Promise<{data: EquipmentQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: EquipmentQueryVariables, query: string}> {
        return requester<{data: EquipmentQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: EquipmentQueryVariables, query: string}, EquipmentQueryVariables>(EquipmentDocument, variables, options);
      },
    equipmentConnection(variables?: EquipmentConnectionQueryVariables, options?: C): Promise<{data: EquipmentConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: EquipmentConnectionQueryVariables, query: string}> {
        return requester<{data: EquipmentConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: EquipmentConnectionQueryVariables, query: string}, EquipmentConnectionQueryVariables>(EquipmentConnectionDocument, variables, options);
      },
    racking(variables: RackingQueryVariables, options?: C): Promise<{data: RackingQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: RackingQueryVariables, query: string}> {
        return requester<{data: RackingQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: RackingQueryVariables, query: string}, RackingQueryVariables>(RackingDocument, variables, options);
      },
    rackingConnection(variables?: RackingConnectionQueryVariables, options?: C): Promise<{data: RackingConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: RackingConnectionQueryVariables, query: string}> {
        return requester<{data: RackingConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: RackingConnectionQueryVariables, query: string}, RackingConnectionQueryVariables>(RackingConnectionDocument, variables, options);
      },
    parts(variables: PartsQueryVariables, options?: C): Promise<{data: PartsQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: PartsQueryVariables, query: string}> {
        return requester<{data: PartsQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: PartsQueryVariables, query: string}, PartsQueryVariables>(PartsDocument, variables, options);
      },
    partsConnection(variables?: PartsConnectionQueryVariables, options?: C): Promise<{data: PartsConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: PartsConnectionQueryVariables, query: string}> {
        return requester<{data: PartsConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: PartsConnectionQueryVariables, query: string}, PartsConnectionQueryVariables>(PartsConnectionDocument, variables, options);
      }
    };
  }
  export type Sdk = ReturnType<typeof getSdk>;

// TinaSDK generated code
import { createClient, TinaClient } from "tinacms/dist/client";

const generateRequester = (
  client: TinaClient,
) => {
  const requester: (
    doc: any,
    vars?: any,
    options?: {
      branch?: string,
      /**
       * Aside from `method` and `body`, all fetch options are passed
       * through to underlying fetch request
       */
      fetchOptions?: Omit<Parameters<typeof fetch>[1], 'body' | 'method'>,
    },
    client
  ) => Promise<any> = async (doc, vars, options) => {
    let url = client.apiUrl
    if (options?.branch) {
      const index = client.apiUrl.lastIndexOf('/')
      url = client.apiUrl.substring(0, index + 1) + options.branch
    }
    const data = await client.request({
      query: doc,
      variables: vars,
      url,
    }, options)

    return { data: data?.data, errors: data?.errors, query: doc, variables: vars || {} }
  }

  return requester
}

/**
 * @experimental this class can be used but may change in the future
 **/
export const ExperimentalGetTinaClient = () =>
  getSdk(
    generateRequester(
      createClient({
        url: "https://content.tinajs.io/2.1/content/9f21479c-bb7e-41c7-ace0-ce51be2b676c/github/main",
        queries,
      })
    )
  )

export const queries = (
  client: TinaClient,
) => {
  const requester = generateRequester(client)
  return getSdk(requester)
}

  